food_stories_project/accounts/api/urls.py
from django.urls import path
from accounts.api.views import *


urlpatterns = [
    path('login/', RecipeAPI.as_view(), name="api_login"),

]

food_stories_project/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from accounts.views import (
    CustomLoginView, logout_page, user_profile, RegisterView,
    ActiveAccountView
)


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name="login_page"),
    path('logout/', LogoutView.as_view(), name="logout_page"),
    path('registration/', RegisterView.as_view(), name="registration"),
    path('profile/', user_profile, name="profile"),
    path('activate/<str:uidb64>/<str:token>/', ActiveAccountView.as_view(), name="activate"),
]

food_stories_project/core/urls.py
from django.urls import path
from core.views import home, contact, ContactView


urlpatterns = [
    path('', home, name="home"),
    path('contact/', ContactView.as_view(), name="contact"),
    # path('export_view/', export_view, name="export_view"),
]

food_stories_project/food_stories/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    path('admin/', admin.site.urls),
    path('api/token/', TokenObtainPairView.as_view(), name='token'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include('stories.api.urls')),
    path('', include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('core.urls')),
    path('', include('stories.urls')),
    path('accounts/', include('accounts.urls')),
)

food_stories_project/accounts/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(_('email address'), unique=True)
    bio = models.TextField('Bio', null=True, blank=True)
    image = models.ImageField('Image', upload_to='user_images/')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username',]

food_stories_project/stories/models.py
from django.db import models
from django.urls import reverse_lazy

from django.contrib.auth import get_user_model

USER = get_user_model()


class Category(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='categories/', null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ('-created_at', 'title')
    
    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Recipe(models.Model):
    title = models.CharField('Title', max_length=50, db_index=True)
    slug = models.SlugField('Slug', max_length=80, db_index=True)
    short_description = models.CharField(max_length=255)
    content = models.TextField()
    image = models.ImageField(upload_to='recipes/')
    category = models.ForeignKey(Category, related_name='recipes', on_delete=models.CASCADE)
    author = models.ForeignKey(USER, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('recipe_detail', kwargs={'pk': self.id})

    # def save(self):
    #     self.slug = self.title
    #     return super().save()


# t = Tag.objects.get(id=1) # title = 'food'
# t.title = 'Tag'
# print(t.title) # Tag

# t2 = Tag.objects.get(id=1)
# print(t2.title) # food

food_stories_project/accounts/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import (
    UsernameField, AuthenticationForm, UserCreationForm
)
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model, password_validation
from accounts.tasks import send_confirmation_mail

User = get_user_model()


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'email',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Password',
    }), validators=(validate_password, ))



class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control',
                'placeholder': 'Password'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'class': 'form-control',
                'placeholder': 'Confirm Password'}),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'First Name'
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Last Name'
            }),
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_active = False
        if commit:
            user.save()
        return user

food_stories_project/accounts/api/views.py
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
)

food_stories_project/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, View
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login as django_login, logout as django_logout
from django.contrib.auth import get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from accounts.tokens import account_activation_token

from accounts.forms import LoginForm, RegistrationForm
from accounts.tasks import send_confirmation_mail

User = get_user_model()


class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm


class RegisterView(CreateView):
    form_class = RegistrationForm
    template_name = 'registration.html'
    success_url = reverse_lazy('login_page')

    def form_valid(self, form):
        result = super().form_valid(form)
        send_confirmation_mail(user=self.object, current_site=get_current_site(self.request))
        return result


class ActiveAccountView(View):

    def get(self, request, *args, **kwargs):
        uidb64 = kwargs['uidb64']
        token = kwargs['token']
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Your account activated!')
            return redirect(reverse_lazy('login_page'))
        else:
            messages.warning(request, 'Something went wrong!')
            return redirect(reverse_lazy('login_page'))


# http://localhost:8000/accounts/login/?next=/idris/
def login_page(request):
    next_page = request.GET.get('next', '/') # '/accounts/profile/'
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password']) 
            if user:
                django_login(request, user)    
                messages.add_message(request, messages.SUCCESS, 'Ugurla login oldunuz')
                return redirect(next_page)
            else:
                messages.add_message(request, messages.ERROR, 'Username ve ya password sehvdir!')
    context = {
        'form': form
    }
    return render(request, 'login.html', context)


def logout_page(request):
    django_logout(request)
    messages.add_message(request, messages.SUCCESS, 'Log out oldunuz!')
    return redirect(reverse_lazy('login_page'))


@login_required
def user_profile(request):
    # user = User.objects.get(id=request.user.id)
    # context = {
    #     'user': 
    # }
    return render(request, 'user-profile.html',)

food_stories_project/accounts/templates/activation.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

<a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}">Click here</a>
{% endautoescape %}

food_stories_project/accounts/templates/login.html
{% extends 'base.html' %}
{% block title %} 
    Login
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
{% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field}}
                            <ul>
                                {% for error in field.errors %}
                                    <li class="alert alert-danger">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="#" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="#" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="{% url 'social:begin' 'facebook' %}" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

food_stories_project/accounts/templates/registration.html
{% extends 'base.html' %}
{% block title %} 
    Login
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="http:////netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
{% endblock %}

{% block content %}
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" class="bg-light p-5 contact-form">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field}}
                            <ul>
                                {% for error in field.errors %}
                                    <li class="alert alert-danger">{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="#" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="#" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="{% url 'social:begin' 'facebook' %}" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>
{% endblock %}

food_stories_project/accounts/templates/user-profile.html
{% extends 'base.html' %}
{% block content %}
    <section class="ftco-section ftco-no-pt ">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="user-profile-side-bar sidebar-wrap">
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About Me</h2>
                            <img src="images/author.jpg" class="img-fluid" alt="Colorlib Template">
                            <div class="text pt-4">
                                <p>Hi! My name is <strong>{{ user.get_full_name }}</strong>, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics,
                                    a large language ocean.</p>
                            </div>
                        </div>
                        {{ user.recipe_set.all }}
                        <div class="sidebar-box ftco-animate user-profile">

                            <a href="single.html" class="btn btn-hover-color py-2">Edit Profile</a>

                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create story </a>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="single.html" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>
                        <div class="sidebar-box p-4 ftco-animate">
                            <form action="#" class="search-form">
                                <div class="form-group">
                                    <span class="icon icon-search"></span>
                                    <input type="text" class="form-control" placeholder="Search">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4"><span>My stories and recipes</span></h2>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">

                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>

                                    <img src="images/blog-1.jpg" class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>
                                    <img src="images/blog-2.jpg" class="img-fluid" alt="Colorlib Template"></a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    <div class="user-events__edit">
                                        <button type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></button>
                                        <button type="button" class="delete-event"><i class="fa fa-trash" aria-hidden="true"></i></button>
                                    </div>
                                    <img src="images/blog-3.jpg" class="img-fluid" alt="Colorlib Template"></a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">Dessert</span><span class="ml-auto pl-3">March 01, 2018</span>
                                    </p>
                                    <h3><a href="#">Tasty &amp; Delicious Foods</a></h3>
                                    <p class="mb-0"><a href="single.html" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </section>
{% endblock %}